local s,id=GetID()
function s.initial_effect(c)
	Gacha2.UnitCharacter(c)
	Gacha3.BattlePhaseUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_SPSUMMON_SUCCESS)
	e1:SetOperation(s.activate)
	c:RegisterEffect(e1)
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local deck=Duel.GetMatchingGroup(nil,tp,LOCATION_DECK,0,nil)
	local deckcount=Duel.GetMatchingGroupCount(nil,tp,LOCATION_DECK,0,nil)
	local refill=Duel.GetMatchingGroup(nil,tp,LOCATION_GRAVE,0,nil)
	local grave=Duel.GetMatchingGroupCount(nil,tp,LOCATION_GRAVE,0,nil)
	local tc=Duel.GetMatchingGroup(nil,tp,LOCATION_EMZONE,0,nil):GetFirst()
	if deckcount+grave==0 then
	Duel.SetLP(tp,444)
	local e1=Effect.CreateEffect(tc)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCode(EFFECT_ADD_SETCODE)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetValue(0xa09)
	tc:RegisterEffect(e1)	
	elseif deckcount+grave<3 then
	local g=Duel.GetMatchingGroup(nil,tp,LOCATION_DECK+LOCATION_GRAVE,0,nil):GetFirst()
	Duel.Remove(g,POS_FACEDOWN,REASON_EFFECT)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetCode(EFFECT_ADD_SETCODE)
	e1:SetRange(LOCATION_REMOVED)
	e1:SetReset(RESET_EVENT+RESET_TOHAND)
	e1:SetValue(0xa03)
	g:RegisterEffect(e1)
	local deckcount2=Duel.GetMatchingGroupCount(nil,tp,LOCATION_DECK,0,nil)
	local grave2=Duel.GetMatchingGroupCount(nil,tp,LOCATION_GRAVE,0,nil)
	if deckcount2+grave2==1 then
	local g2=Duel.GetMatchingGroup(nil,tp,LOCATION_DECK+LOCATION_GRAVE,0,nil):GetFirst()
	Duel.Remove(g2,POS_FACEDOWN,REASON_EFFECT)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e2:SetCode(EFFECT_ADD_SETCODE)
	e2:SetRange(LOCATION_REMOVED)
	e2:SetReset(RESET_EVENT+RESET_TOHAND)
	e2:SetValue(0xa03)
	g2:RegisterEffect(e2) end
	Duel.SetLP(tp,444)
	local e3=Effect.CreateEffect(tc)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
	e3:SetCode(EFFECT_ADD_SETCODE)
	e3:SetRange(LOCATION_ONFIELD)
	e3:SetValue(0xa09)
	tc:RegisterEffect(e3)
	else
	if Duel.GetMatchingGroupCount(nil,tp,LOCATION_DECK,0,nil)<3 then
	Duel.SendtoGrave(deck,REASON_RULE)
	Duel.SendtoDeck(refill,nil,SEQ_DECKSHUFFLE,REASON_RULE)
	Duel.SendtoDeck(deck,nil,0,REASON_RULE)	end
	local g=Duel.GetDecktopGroup(tp,3)
	if #g<3 then return end
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(id,0))
	local sg1=g:Select(tp,1,1,nil)
	Duel.Remove(sg1,POS_FACEDOWN,REASON_EFFECT)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetCode(EFFECT_ADD_SETCODE)
	e1:SetRange(LOCATION_REMOVED)
	e1:SetReset(RESET_EVENT+RESET_TOHAND)
	e1:SetValue(0xa03)
	sg1:GetFirst():RegisterEffect(e1)
	g:Sub(sg1)
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(id,0))
	local sg2=g:Select(tp,1,1,nil)
	Duel.Remove(sg2,POS_FACEDOWN,REASON_EFFECT)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetCode(EFFECT_ADD_SETCODE)
	e1:SetRange(LOCATION_REMOVED)
	e1:SetReset(RESET_EVENT+RESET_TOHAND)
	e1:SetValue(0xa03)
	sg2:GetFirst():RegisterEffect(e1)
	g:Sub(sg2)	
	Duel.SendtoGrave(g,REASON_EFFECT) end
end