local s,id=GetID()
function s.initial_effect(c)
	Gacha2.UnitCharacter(c)
	Gacha3.BattlePhaseUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCode(EFFECT_UPDATE_ATTACK)
	e1:SetCondition(s.cond)
	e1:SetTargetRange(LOCATION_ONFIELD,0)
	e1:SetTarget(s.filter)
	e1:SetValue(100)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e2)
end
function s.cond(e)
	return Duel.GetTurnPlayer()~=e:GetHandlerPlayer() and Duel.IsBattlePhase()
end
function s.filter(e,c)
	return not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE) and c:IsLevelAbove(3) and not c:IsSetCard(0xc03)
end