--Gacha's Duel is Kami Game
Gacha3={}

--협공협방 유틸
function Gacha3.BattlePhaseUnit(c)
	Gacha3.DuelAtkUnit(c)
	Gacha3.SoloDefUnit(c)
end

--협동공격
function Gacha3.DuelAtkUnit(c)
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
    e1:SetCode(EVENT_BATTLE_START)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCondition(Gacha3.battlecon)
	e1:SetOperation(Gacha3.battleop)
    c:RegisterEffect(e1)
end
function Gacha3.battlecon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return Duel.GetAttacker():IsControler(tp) and
	Duel.IsExistingMatchingCard(Gacha3.battlefilter,tp,LOCATION_ONFIELD,0,1,nil)
end
function Gacha3.battlefilter(c)
	return c:IsPosition(POS_FACEUP_ATTACK) and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE)
end
function Gacha3.battlefilter2(c)
	return c:IsPosition(POS_FACEUP_ATTACK) and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE) and not c:IsSetCard(0xa01)
end
function Gacha3.battleop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DEFENSE_ATTACK)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetValue(1)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE_CAL)
		c:RegisterEffect(e1)
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
	if c:IsSetCard(0xa01) then return end
	if Duel.IsExistingMatchingCard(Gacha3.battlefilter2,tp,LOCATION_ONFIELD,0,1,nil)
	and Duel.SelectYesNo(tp,aux.Stringid(11020001,0)) then
	local g=Duel.SelectMatchingCard(tp,Gacha3.battlefilter2,tp,LOCATION_ONFIELD,0,0,1,nil)
	local tc=g:GetFirst()
	if #g==0 then return end
	Duel.ChangePosition(tc,POS_FACEUP_DEFENSE)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_ADD_SETCODE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetValue(0xa04)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_ADD_SETCODE)
		e3:SetRange(LOCATION_ONFIELD)
		e3:SetValue(0xa04)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		tc:RegisterEffect(e3)
		local def=tc:GetDefense()
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_UPDATE_DEFENSE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE_CAL)
		e4:SetValue(def)
		c:RegisterEffect(e4)
		if tc:IsCode(11060001) and Duel.GetAttackTarget()==nil then
		Gacha3.UrsaUnit(e,tp,eg,ep,ev,re,r,rp)	end
	end
end

--작은곰자리
function Gacha3.UrsaUnit(e,tp,eg,ep,ev,re,r,rp)
	local ag=Duel.GetMatchingGroup(Gacha3.Ursafilter,tp,0,LOCATION_ONFIELD,nil)
	if #ag==0 then return end
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetTargetRange(0,LOCATION_ONFIELD)
		e1:SetTarget(aux.TargetBoolFunction(Card.IsLevelBelow,4))
		e1:SetValue(0xb02)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE_CAL)
		e:GetHandler():RegisterEffect(e1)
		ag:ForEach(function(tc)
		local e2=Effect.CreateEffect(e:GetHandler())
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_CANNOT_TRIGGER)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetTargetRange(LOCATION_ONFIELD,0)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE_CAL)
		tc:RegisterEffect(e2)
	end)
end
function Gacha3.Ursafilter(c)
	return c:IsPosition(POS_FACEUP_ATTACK) and c:IsLevelBelow(4) and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE)
end

--1체방어(1 1체가드,2 액티브저격1체방어,3 레스트저격1체방어)
function Gacha3.SoloDefUnit(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e1:SetCode(EVENT_BATTLE_START)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCondition(Gacha3.btcountercon)
	e1:SetTarget(Gacha3.btcountertg)
	e1:SetOperation(Gacha3.btcounterop)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e2:SetCode(EVENT_BATTLE_START)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCondition(Gacha3.btcountercon2)
	e2:SetTarget(Gacha3.btcountertg)
	e2:SetOperation(Gacha3.btcounterop2)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e3:SetCode(EVENT_BATTLE_START)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e3:SetCondition(Gacha3.btcountercon3)
	e3:SetOperation(Gacha3.btcounterop3)
	c:RegisterEffect(e3)
end
function Gacha3.btcountercon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return Duel.GetAttacker():IsControler(1-tp) and Duel.GetAttackTarget()==nil 
	and c:IsAttackPos() and not c:IsSetCard(0xb02)
end
function Gacha3.btcountertg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
	Duel.SetChainLimit(aux.FALSE)
end
function Gacha3.btcounterfilter(c)
	return c:IsAttackPos() and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE) 
	and not (c:IsSetCard(0xa02) or c:IsSetCard(0xb02))
end

function Gacha3.btcounterop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
	if Duel.IsExistingMatchingCard(Gacha3.btcounterfilter,tp,LOCATION_ONFIELD,0,1,nil)
	and not (c:IsSetCard(0xa02) or c:IsSetCard(0xb02)) and Duel.SelectYesNo(tp,aux.Stringid(11020001,1)) then
	local g=Duel.SelectMatchingCard(tp,Gacha3.btcounterfilter,tp,LOCATION_ONFIELD,0,0,1,nil)
	local tc=g:GetFirst()
	if #g==0 then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetValue(0xa06)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e1) end
	if #g==1 then
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_ADD_SETCODE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetValue(0xa05)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(tc)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_ADD_SETCODE)
		e3:SetRange(LOCATION_ONFIELD)
		e3:SetValue(0xa05)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		tc:RegisterEffect(e3)
		Duel.ChangePosition(tc,POS_FACEUP_DEFENSE)
		local def=tc:GetDefense()
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_UPDATE_DEFENSE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetValue(def)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(tc)
		e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e5:SetCode(EVENT_LEAVE_FIELD)
		e5:SetRange(LOCATION_ONFIELD)
		e5:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e5:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e5:SetCondition(Gacha3.btcounterdescon2)
		e5:SetOperation(Gacha3.btcounterdesop2)
		tc:RegisterEffect(e5) end
		else
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_SINGLE)
		e6:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e6:SetCode(EFFECT_ADD_SETCODE)
		e6:SetRange(LOCATION_ONFIELD)
		e6:SetValue(0xa06)
		e6:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e6) end
		local e7=Effect.CreateEffect(c)
		e7:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
		e7:SetCode(EVENT_PRE_DAMAGE_CALCULATE)
		e7:SetRange(LOCATION_ONFIELD)
		e7:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e7:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		e7:SetOperation(Gacha3.btcoutertgop)
		c:RegisterEffect(e7)
end
function Gacha3.btcoutertgop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.CalculateDamage(at,c)
end
function Gacha3.btcountercon2(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetAttacker():IsControler(1-tp) and e:GetHandler():IsAttackPos() and Duel.GetAttackTarget()==e:GetHandler()
end
function Gacha3.btcounterfilter2(c)
	return c:IsAttackPos() and not c:IsLocation(LOCATION_EMZONE+LOCATION_FZONE)
	and not (c:IsSetCard(0xa02) or c:IsSetCard(0xb02))
end
function Gacha3.btcounterop2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local at=Duel.GetAttacker()
	Duel.ChangePosition(c,POS_FACEUP_DEFENSE)
		local g=Duel.SelectMatchingCard(tp,Gacha3.btcounterfilter2,tp,LOCATION_ONFIELD,0,0,1,c)
		tc=g:GetFirst()
		if #g==0 then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_ADD_SETCODE)
		e1:SetRange(LOCATION_ONFIELD)
		e1:SetValue(0xa07)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e1) end
		if #g==1 then 	
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_ADD_SETCODE)
		e2:SetRange(LOCATION_ONFIELD)
		e2:SetValue(0xa05)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(tc)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetCode(EFFECT_ADD_SETCODE)
		e3:SetRange(LOCATION_ONFIELD)
		e3:SetValue(0xa05)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		tc:RegisterEffect(e3)
		Duel.ChangePosition(tc,POS_FACEUP_DEFENSE)
		local def=tc:GetDefense()
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetCode(EFFECT_UPDATE_DEFENSE)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetValue(def)
		e4:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(tc)
		e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e5:SetCode(EVENT_LEAVE_FIELD)
		e5:SetRange(LOCATION_ONFIELD)
		e5:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e5:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e5:SetCondition(Gacha3.btcounterdescon2)
		e5:SetOperation(Gacha3.btcounterdesop2)
		tc:RegisterEffect(e5)	end
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_FIELD)
		e6:SetRange(LOCATION_ONFIELD)
		e6:SetCode(EFFECT_CHANGE_DAMAGE)
		e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e6:SetTargetRange(1,0)
		e6:SetReset(RESET_PHASE+PHASE_DAMAGE)
		e6:SetValue(0)
		c:RegisterEffect(e6)
end
function Gacha3.btcounterdesfilter2(c)
	return c:IsReason(REASON_BATTLE)
end
function Gacha3.btcounterdescon2(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(Gacha3.btcounterdesfilter2,1,nil)
end
function Gacha3.btcounterdesop2(e,tp,eg,ep,ev,re,r,rp)
	Duel.Destroy(e:GetHandler(),REASON_BATTLE)
end
function Gacha3.btcountercon3(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetAttacker():IsControler(1-tp) and e:GetHandler():IsDefensePos() and Duel.GetAttackTarget()==e:GetHandler()
end
function Gacha3.btcounterop3(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetRange(LOCATION_ONFIELD)
	e1:SetCode(EFFECT_CHANGE_DAMAGE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_PHASE+PHASE_DAMAGE)
	e1:SetValue(0)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetCode(EFFECT_ADD_SETCODE)
	e2:SetRange(LOCATION_ONFIELD)
	e2:SetValue(0xa08)
	e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_DAMAGE)
	c:RegisterEffect(e2)
end